version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      volumes:
        - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
      command:
        - start-dev --log-console-color true --import-realm
       # - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
      environment:
        KC_DB_VENDOR: POSTGRES
        KC_DB_ADDR: postgres
        KC_DB_DATABASE: keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_SCHEMA: public
        KC_DB_PASSWORD: password
        KEYCLOAK_ADMIN: httpyac
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_HOSTNAME: localhost
      ports:
        - 8080:8080
        - 9990:9990
      depends_on:
        - postgres