version: "3.8"
services:
  postgres:
    image: postgres:15.5-alpine3.19
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend

  auth:
    image: quay.io/keycloak/keycloak:23.0.3
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm.json
      - KC_PROXY=edge
      - PROXY_ADDRESS_FORWARDING=true
      - LOG_LEVEL=ALL
      - KEYCLOAK_IMPORT=./realm-export.json
      #Don't know how to connect to postgres database. NONE of these seems work:
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_DATABASE=postgres
      - KC_DB_VENDOR=POSTGRES
      - KC_DB_ADDR=postgres
      - KC_DB_DATABASE=keycloak
      - KC_DB_USER=keycloak
      - KC_DB_SCHEMA=public
      - KC_DB_PASSWORD=password
      - DATABASE=postgres
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
    depends_on:
      - postgres
    command:
      - start-dev
    volumes:
      - ./auth/import:/opt/keycloak/data/import
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  postgres_data:
    driver: local
